services:
  # Base de datos Postgres
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: ruleta_user
      POSTGRES_PASSWORD: ruleta_pass
      POSTGRES_DB: ruletadb
    volumes:
      - postgres_data:/var/lib/postgresql/data   # <- renombrado aquí
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "ruleta_user", "-d", "ruletadb"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - ruleta_network

  # Servicio backend (Python/Flask)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ruleta_backend
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - FLASK_SKIP_DOTENV=1            
      - FLASK_ENV=production
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=7002
      - DATABASE_URL=postgresql://ruleta_user:ruleta_pass@postgres:5432/ruletadb
    volumes:
      - ./backend:/app
    ports:
      - "7002:5000"
    command: >
      sh -c "flask db upgrade && python app.py"
    networks:
      - ruleta_network
    restart: unless-stopped

  # Servicio frontend (React con nginx)
  frontend:
    build:
      context: ./mi-proyecto
      dockerfile: Dockerfile
    container_name: ruleta_frontend
    ports:
      - "7001:80"
    depends_on:
      - backend
    networks:
      - ruleta_network
    restart: unless-stopped

volumes:
  postgres_data: 

networks:
  ruleta_network:
    driver: bridge