"""Migración de todos los modelos

Revision ID: 4f80662358a8
Revises: 11b5c8d4ffd6
Create Date: 2025-05-10 23:14:00.707014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f80662358a8'
down_revision = '11b5c8d4ffd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grupo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alumno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matricula', sa.String(length=12), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('id_grupo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_grupo'], ['grupo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incidencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.Column('duracion', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['id_categoria'], ['categoria.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sorteo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_grupo', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('id_profesor', sa.Integer(), nullable=False),
    sa.Column('id_incidencia', sa.Integer(), nullable=False),
    sa.Column('id_alumno', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_alumno'], ['alumno.id'], ),
    sa.ForeignKeyConstraint(['id_grupo'], ['grupo.id'], ),
    sa.ForeignKeyConstraint(['id_incidencia'], ['incidencia.id'], ),
    sa.ForeignKeyConstraint(['id_profesor'], ['profesor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comentario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('id_sorteo', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_sorteo'], ['sorteo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comentario')
    op.drop_table('sorteo')
    op.drop_table('incidencia')
    op.drop_table('alumno')
    op.drop_table('grupo')
    op.drop_table('categoria')
    # ### end Alembic commands ###
