"""se agrega proyecto a los grupos

Revision ID: 821462e1980c
Revises: 0402a5699314
Create Date: 2025-05-23 22:04:41.691358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '821462e1980c'
down_revision = '0402a5699314'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grupo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_proyecto1', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('id_proyecto2', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'proyecto', ['id_proyecto1'], ['id'])
        batch_op.create_foreign_key(None, 'proyecto', ['id_proyecto2'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grupo', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_proyecto2')
        batch_op.drop_column('id_proyecto1')

    # ### end Alembic commands ###
