"""cambios

Revision ID: d3e7e7b0ddf7
Revises: 4f80662358a8
Create Date: 2025-05-23 20:50:35.948507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3e7e7b0ddf7'
down_revision = '4f80662358a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sorteo', schema=None) as batch_op:
        batch_op.alter_column('id_alumno',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sorteo', schema=None) as batch_op:
        batch_op.alter_column('id_alumno',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
